name: dbt CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-compile-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install dbt-core dbt-snowflake

      - name: Create Dummy Profile
        run: |
          mkdir -p ci_profiles
          cat <<EOF > ci_profiles/profiles.yml
          public_data_mart:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ci_test
                user: ci_test
                password: ci_test
                role: ci_test
                database: ci_test
                warehouse: ci_test
                schema: ci_test
          EOF
        working-directory: ./dbt/public_data_mart

      - name: Run dbt deps
        run: dbt deps --profiles-dir ci_profiles
        working-directory: ./dbt/public_data_mart

      # - name: Run dbt compile
      # dbt에서 snonwflake 접속 정보를 이용하므로 실제 컴파일에서 제외, parse만 진행하도록 변경
      #   run: dbt compile --profiles-dir ci_profiles
      #   working-directory: ./dbt/public_data_mart

      - name: Run dbt parse
        # compile 대신 parse를 사용하여 DB 접속 없이 테스트를 완료합니다.
        run: dbt parse --profiles-dir ci_profiles
        working-directory: ./dbt/public_data_mart        